### ISSUE TITLE
Notification shows it runs on http://0.0.0.0:16163

### ISSUE THREAD

**Issue by 404dev404** [Constaline/unblockneteasemusic-desktop#1]
Hello,

Thanks for dev and packing up.

When I run the app. I got a notification shows it runs on http://0.0.0.0:16163

![image](https://user-images.githubusercontent.com/31719956/98471040-a7a0d800-21b7-11eb-88b9-68fb2e0c7bd4.png)

I tried to set proxy on both http://0.0.0.0:16163 and http://127.0.0.1:16163 but none of them works. (Notification: 
![image](https://user-images.githubusercontent.com/31719956/98471082-efbffa80-21b7-11eb-80b2-70d8b648d448.png)
)

**Comment by Constaline** [comment]
Maybe port 16163 is already using.  Please download version [1.1.1](https://github.com/Constaline/unblockneteasemusic-desktop/releases/tag/1.1.1).

**Comment by Constaline** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/608

**Comment by Constaline** [comment]
Please download version [1.1.3](https://github.com/Constaline/unblockneteasemusic-desktop/releases/tag/1.1.3)

**Comment by 404dev404** [comment]
> Please download version [1.1.3](https://github.com/Constaline/unblockneteasemusic-desktop/releases/tag/1.1.3)

Thanks!

**Comment by 404dev404** [comment]
Sorry, I still get the same error. logs:

[2020-11-09T09:40:09.161] [INFO] console - HTTP Server running @ http://0.0.0.0:16163
[2020-11-09T09:41:54.885] [INFO] console - HTTP Server running @ http://0.0.0.0:16163
[2020-11-09T09:42:12.505] [INFO] console - HTTP Server running @ http://0.0.0.0:16163

**Comment by 404dev404** [comment]
Is that possible to customize the HTTP (by default we have: 127.0.0.1)?

**Comment by Constaline** [comment]
default address in UnblockNeteaseMusic is 'localhost'. ( [code](https://github.com/nondanee/UnblockNeteaseMusic/blob/master/src/hook.js#L205) )

**Comment by Constaline** [comment]
try to set proxy 'http://127.0.0.1:16163' in NeteaseMusic client

![image](https://user-images.githubusercontent.com/10860808/98557003-a0281e80-22de-11eb-9ed2-e75180f9988d.png)

**Comment by 404dev404** [comment]
OK. I see. Although it still shows 0.0.0.0:16163, when I fill the setting with 127.0.0.1, it works! Thanks a lot. 👍

**Comment by Constaline** [comment]
emmmm…the notification has problem…
