### ISSUE TITLE
是不是不能用了呀

### ISSUE THREAD

**Issue by 857857-lps** [Constaline/unblockneteasemusic-desktop#10]
显示测试代理正常  但是没有网络  不知道什么情况  请问作者能解答一下吗

**Comment by HuangLuxuan** [comment]
+1可能是网易云改了什么东西……

**Comment by Constaline** [comment]
请尝试更换旧版客户端  https://github.com/nondanee/UnblockNeteaseMusic/issues/824#issuecomment-1186264741
