### ISSUE TITLE
播放遇到网络不给力弹窗

### ISSUE THREAD

**Issue by zzh567** [Constaline/unblockneteasemusic-desktop#19]
修改代理后点击测试，提示代理可使用。但是重启客户端后播放歌曲提示网络不给力，因此无法播放。另外不使用代理时是正常播放的，并非本地网络问题。是否是网易云客户端版本问题？还是有其他问题？

![屏幕截图 2024-12-10 000622](https://github.com/user-attachments/assets/bf710d25-a063-479d-a8ca-9de370fce607)
![屏幕截图 2024-12-10 000730](https://github.com/user-attachments/assets/353a16c5-b7df-4902-8dd6-514ab9c6ab53)

**Comment by zzh567** [comment]
已解决，项目https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic中提到

新版网易云客户端有更严格的 SSL 验证，如果碰到了连接失败的问题，可以启用 HTTPS 端口并安装 UnblockNeteaseMusic CA 证书。右键点击 QtUnblockNeteaseMusic.exe，选择 以管理员身份运行，然后点击 高级 菜单中的 安装证书。

安装此项目中证书后可正常播放

**Comment by Constaline** [comment]
谢谢。后续参考下QtUnblockNeteaseMusic安装证书方法。
