### ISSUE TITLE
Error: read ECONNRESET     at TLSWrap.onStreamRead

### ISSUE THREAD

**Issue by timesponge** [Constaline/unblockneteasemusic-desktop#3]
[2020-11-27T12:20:28.790] [INFO] console - Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:200:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

这是我的日志，求问，出现这个问题怎么解决？

**Comment by Constaline** [comment]
ECONNRESET 是连接被重置了……先检查一下网络？ 

（不知道是哪个的 error 事件……

**Comment by Constaline** [comment]
或者先加这个防止进程退出
```
process.on('uncaughtException', e => {
	console.log(e.stack)
})
```

**Comment by timesponge** [comment]
是我的网络环境问题，要配置代理，感谢
