### ISSUE TITLE
无法打开鲸鱼特效和黑胶VIP等页面

### ISSUE THREAD

**Issue by Rothes** [Constaline/unblockneteasemusic-desktop#6]
无法打开鲸鱼特效和黑胶VIP等页面
可参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/48

版本: 1.1.7
网易云版本: 2.7.5(Build 198554)
系统环境: Windows 10 20H2

**Comment by Constaline** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/537#issuecomment-629621533

**Comment by Constaline** [comment]
请下载最新版本 [1.1.8](https://github.com/Constaline/unblockneteasemusic-desktop/releases/tag/1.1.8)
