### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by pinkpeachabc** [Constaline/unblockneteasemusic-desktop#7]
这两天好像失效了，获取不到歌曲了。

**Comment by Constaline** [comment]
请下载最新版本 [1.2.0](https://github.com/Constaline/unblockneteasemusic-desktop/releases/tag/1.2.0)

**Comment by pinkpeachabc** [comment]
> 请下载最新版本 [1.2.0](https://github.com/Constaline/unblockneteasemusic-desktop/releases/tag/1.2.0)

感谢修复
