### ISSUE TITLE
bb音源无法使用

### ISSUE THREAD

**Issue by if1y** [Constaline/unblockneteasemusic-desktop#8]
加上 Referrer 能够正常访问音源文件

**Comment by Constaline** [comment]
请下载最新版本 [1.3.1](https://github.com/Constaline/unblockneteasemusic-desktop/releases/tag/1.3.1)

**Comment by if1y** [comment]
测试还是无法播放，日志有源文件地址输出，但设备上播放失败

**Comment by Constaline** [comment]
能否给个歌曲名测试一下？

**Comment by if1y** [comment]
一般我都是用周杰伦来测试解锁，反正就都不行，链接拿出到浏览器+Chrome插件改Referrer没有问题
这是log截取：
```
[INFO] console - current source: [ 'bilibili' ]
[1400394238] 双截棍 (Live)
http://upos-sz-mirrorks3.bilivideo.com/ugaxcode/m190509ws3sl4ruxmbikgozc2hypzz4n-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1624839857&gen=playurlv2&os=ks3bv&oi=1781843068&trid=e5feb1629e5144d08fd63fc0ff07203dB&platform=pc&upsig=2c21ea2af9f60f1c73a8365819608e03&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&orderid=0,1&logo=00000000
[1400391910] 开不了口 (Live)
http://upos-sz-mirrorks3.bilivideo.com/ugaxcode/m201011a23oy5pfgok0v3034o2psyrar-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1624839872&gen=playurlv2&os=ks3bv&oi=1781843068&trid=203523a57bc143c3abcd95dc43935c61B&platform=pc&upsig=55e5bb82efcede8b2b58f40650046578&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&orderid=0,1&logo=00000000
[1400391913] 夜曲 + 窃爱 (Live)
http://upos-sz-mirrorks3.bilivideo.com/ugaxcode/m200827a212x9b9c5wzvbl26kupjdl1a-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1624839878&gen=playurlv2&os=ks3bv&oi=1781843068&trid=397454a447ec43428e75bda509494171B&platform=pc&upsig=cc9ffc0581fa0d3b28834ad736012453&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&orderid=0,1&logo=00000000
[1400391959] 爱的飞行日记 (Live)
http://upos-sz-mirrorks3.bilivideo.com/ugaxcode/m200827a21tk9tt5txmcwh13v7gmq7il-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1624839882&gen=playurlv2&os=ks3bv&oi=1781843068&trid=ee180269ef3b44ddaeebe2db1d5e2835B&platform=pc&upsig=15b2f0a4b62716cf1db383a939a0dc34&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&orderid=0,1&logo=00000000
[1400391959] 爱的飞行日记 (Live)
http://upos-sz-mirrorks3.bilivideo.com/ugaxcode/m200827a21tk9tt5txmcwh13v7gmq7il-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1624839883&gen=playurlv2&os=ks3bv&oi=1781843068&trid=8058163942e6438d97a16f394eaa761aB&platform=pc&upsig=8c7d1438b75285fa8b29bf8a2aff63a3&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&orderid=0,1&logo=00000000
[1400394285] 半岛铁盒 (Live)
http://upos-sz-mirrorks3.bilivideo.com/ugaxcode/m201011a21zvxip1l6o5dx1oh0v0hvxs-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1624839896&gen=playurlv2&os=ks3bv&oi=1781843068&trid=ae372eb22c014dea9e732070fb7dd542B&platform=pc&upsig=bbe890556a08d370a38e08df037f3c1e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&orderid=0,1&logo=00000000
```

**Comment by Constaline** [comment]
已经是加了 referer https://github.com/Constaline/unblockneteasemusic-desktop/commit/a7fe13aaeea640cf879e675045557956d7893674

**Comment by Constaline** [comment]
参考 https://github.com/nondanee/UnblockNeteaseMusic/pull/711#issuecomment-788275944

**Comment by Constaline** [comment]
请下载版本 [1.3.2](https://github.com/Constaline/unblockneteasemusic-desktop/releases/tag/1.3.2)

**Comment by if1y** [comment]
嗯，之前就是看的那个 pr 找到你这个仓库的，你的源码解决了 referrer 问题，照这样修改原版同样可用。
然后最近就把你的程序装在了某轻量windows上，代理回本地设备使用，然后就发现还是有 referrer 问题，所以有此 issue。

最初是拿windows版本的网易云客户端使用本程序，bb音源正常，并且我也看过源码，是在程序本身请求音源的时候就加入了referrer，下载到文件后再转发给接入代理的设备，所以按理说应该没什么问题。

今天试着对比了一下，windows客户端使用轻量的代理能正常播放，依然**出问题的设备是 iOS HD 客户端，那应该是客户端或者iOS设备的差异性了，具体什么差异导致的不清楚**。

**Comment by if1y** [comment]
补充：我照着你的源码，对nondanee**原版修改增加referrer之后，跑起来的话是能够正常给 iOS HD 客户端使用的**

**Comment by Constaline** [comment]
晚点对比一下之前的源码看看。合并了另一版本的 UnblockNeteaseMusic 可能出现问题。 = =。

**Comment by Constaline** [comment]
升级了 electron@12.0.7 之后好像可以正常播放bb音源了。   [下载地址](https://github.com/Constaline/unblockneteasemusic-desktop/releases/tag/1.3.3)

**Comment by if1y** [comment]
还是不行。

我排查了播放设备这边的请求日志，才发现本项目并没有对源文件放在代理中包裹传输，而是把源文件地址交给设备端直接请求。

这一点与[原版项目](https://github.com/nondanee/UnblockNeteaseMusic)的处理逻辑不太一样，之前我只是看了部分代码、本项目返回源文件链接的那一处代码一致，想当然就以为结果也一致，直到今天从设备端抓包才发现不一样。

至少从设备抓包看，请求的是其它平台的音乐文件链接，请求里 Referrer 也是 `music.163.com`，所以会失败。
正常情况使用原版项目会是 `https://music.163.com/package/***` 这样的包裹形式。

**Comment by Constaline** [comment]
好的谢谢。这边再看一下。

**Comment by Constaline** [comment]
请问 iOS 设备是使用 Shadowrocket 代理吗？

**Comment by if1y** [comment]
> 请问 iOS 设备是使用 Shadowrocket 代理吗？

Shadowrocket 和 Loon 均有测试使用。
分别在这两个应用中添加http代理，参数为 `IP:PORT`，并配置分流。
因为都是http代理，所以应该表现一致。实测也确实如此，日志显示的都是请求 `upos-sz-mirrorks3.bilivideo.com` 而非 `https://music.163.com/package/...`。

**Comment by Constaline** [comment]
之前的版本应该是改动了 hook.js ，后续好像是覆盖了。 _(:3」∠)_
把`upos-sz-mirrorks3.bilivideo.com`，加到`lib/UnblockNeteaseMusic/src/hook.js`中

```javascript
hook.target.host = new Set([
	'music.163.com',
	'interface.music.163.com',
	'interface3.music.163.com',
	'apm.music.163.com',
	'apm3.music.163.com',
	// 'mam.netease.com',
	// 'api.iplay.163.com', // look living
	// 'ac.dun.163yun.com',
	// 'crash.163.com',
	// 'clientlog.music.163.com',
	// 'clientlog3.music.163.com'

	// 这个位置加一行
	'upos-sz-mirrorks3.bilivideo.com',
])
```

**Comment by if1y** [comment]
您好，我用最新源码编译测试了，已修改 hook.js，但还是不行。

- 日志有出现 `upos-sz-mirrorcos` 等一些其它CDN，我都在发现后加进去重新测试过
- iOS代理工具尝试强制指定 `bilivideo.com` 域名走到网易云代理，所以即使是没有做成 `https://music.163.com/package/...` 形式应该也能让流量传给代理处理
- iOS代理工具请求日志依然显示 `bilivideo.com` 的 Referrer 是 `http://music.163.com`

我觉得问题还是这个 Referrer。
但检查程序代码又确实有指定 Referrer了。
本代理在 Windows 和 Android 测试也都可用。
挺奇怪的。

**Comment by Constaline** [comment]
感谢您的支持。很抱歉，此问题暂时没有头绪。`_(:3」∠)_`

**Comment by if1y** [comment]
没事，也感谢你的辛苦努力。
挺奇怪的问题，哈哈。

就先这样吧，用其它音源，以后要是有机会处理再说🤗

**Comment by Constaline** [comment]
或者可以把 UnblockNeteaseMusic 原版的代码用 [pkg](https://github.com/vercel/pkg) 打包一下运行

**Comment by Constaline** [comment]
可以参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/771

**Comment by Constaline** [comment]
用 `lib/UnblockNeteaseMusic` 的代码打了一个包

需要设置代理地址 `127.0.0.1`，端口 `8080`

[unblockneteasemusic.zip](https://github.com/Constaline/unblockneteasemusic-desktop/files/8087063/unblockneteasemusic.zip)

**Comment by if1y** [comment]
啊有道理，机器上是有Node.js的，所以直接跑原版也可以，没反应过来😆

**Comment by Constaline** [comment]
用 [pkg](https://github.com/vercel/pkg) 打包成 exe 后设置开机启动就行

**Comment by Constaline** [comment]
在 `lib/UnblockNeteaseMusic/app.js`  中用 `process.argv` 写好传入的参数就行
